steps:
- name: 'ubuntu'
  args: ['echo', 'hello world!']
options:
  workerPool: 'projects/834272249548/locations/us-east1/workerPools/test-pool'
gitConfig:
  http:
    proxySecretVersionName: 'projects/834272249548/secrets/test-proxy/versions/4'
